expname: 
num_epoch: 1000
gpu: 0
valid_every: 10
log_every: 5
save_model_every: 1000
checkpoint_filepath: false # false for no checkpoint

GT_dirpath: /data1/why/full_data/full_data/output
input_dirpath: /data1/why/full_data/full_data/input

transforms:
  crop: 512 # crop size, false for not cropping.
  resize: 1.5 # downsample factor. 0.x for upsample; false for not resizing.
  horizon_flip: true
  vertical_flip: true

losses:
  ltvLoss: 0.1
  CosSimilarity: 0.1

predict_illumination: true